name: Apply and Destroy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Apply
        uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run
          message: |
            Apply (commit: ${{ github.SHA }})
          type: apply
          wait-for-completion: true

      - name: Destroy
        uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          workspace: tfe-run
          message: |
            Destroy (commit: ${{ github.SHA }})
          type: destroy
          wait-for-completion: true
